Update patch set 1
Patch Set 1:

While most devices aren't actually using the telephony extension, this is needed to actually prevent the NoClassDefFoundError when dialling (and probably some other telephony-related functions)

Patch-set: 1