Update patch set 1
Patch Set 1:

My build for android-7.1.2_r2 fails that it can't find "gr_sys_font", which is added in this patch. I'm not sure if I'm missing something, I did a repo init with:

repo init https://review.lineageos.org/LineageOS/android -b refs/changes/10/167810/3

Did a repopick -t android-7.1.2_r2 to make sure I had all patches on gerrit.

Build error message:

vendor/cm/charger/healthd_board_cm.cpp:86:18: error: use of undeclared identifier 'gr_sys_font'
    gr_font_size(gr_sys_font(), &font_x, &font_y);
                 ^
vendor/cm/charger/healthd_board_cm.cpp:87:24: error: use of undeclared identifier 'gr_sys_font'
    int w = gr_measure(gr_sys_font(), cap_str);
                       ^
vendor/cm/charger/healthd_board_cm.cpp:93:13: error: use of undeclared identifier 'gr_sys_font'
    gr_text(gr_sys_font(), x, y + font_y / 2, cap_str, 0);


If more information is needed I'm glad to help.

Patch-set: 1
Reviewer: Jordy van Wolferen <16428@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0